### ISSUE TITLE
Tags with multiple words not being grouped when exploring Ordered Tags

### ISSUE THREAD

**Issue by ocaisa** [ncsa/clowder#13]
We use tags such as `Classical MD` for our content but when we go to `<instance>/tags/list/ordered` the words are separated out to form two different entries `Classical` and `MD`. On the data themselves they appear correctly.

**Comment by robkooper** [comment]
Are you using elasticsearch plugin?

**Comment by robkooper** [comment]
Also as a FYI, we are in the progress of migrating this repository to https://github.com/clowder-framework/clowder

**Comment by ocaisa** [comment]
I believe we are but the honest answer is I don't really know (I don't think we've modified those settings in our configuration and the elasticsearch docker container is up and running).

The related settings in our `custom.conf` are 
```
custom.conf:elasticsearchSettings.clusterName="clowder"
custom.conf:elasticsearchSettings.serverAddress="elasticsearch"
custom.conf:elasticsearchSettings.serverPort="9300"
```
In our ```docker-compose.yml``` we have
```
# elasticsearch to allow indexing
elasticsearch:
    image: elasticsearch:2
    command: elasticsearch -Des.cluster.name="clowder"
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes:
        - ${PWD}/esdata:/usr/share/elasticsearch/data
```
